### PR TITLE
Added support for city, region & lat/long

### PR DESCRIPTION
**Pull request by missinglink**

### CODE REVIEW

**Comment by missinglink** [comment]
Any action on this PR? Let me know if you need any changes.

**Comment by garo** [comment]
Tried to merge, however I don't see how the line
global.geodatadir = path.join(__dirname, '/../data/');
does anything.

As I look on the geoip-lite/lib/geoip.js, it tries to load the city data files like this:
ifile = path.join(__dirname, '/../data/geoip-city-names.dat');
but the __dirname points to the path node_modules/geoip-lite/lib, so it can't find the data files under /data. Do you have any good ideas how to solve this?

**Comment by missinglink** [comment]
Apologies, I'll have another look at it today.

When I last left it all the tests were passing and I was getting city level accuracy.

I've probably forgotten to commit the files or omitted install instructions.

**Comment by missinglink** [comment]
this was super old so I just closed it

**Pull request closed without merging**
